version: '2'
services:
  sapper:
    image: jbracho/pm2-sapper:1.0
    container_name: sapper-app
    restart: always
    volumes:
      - ~/app/:/usr/src/app/sapperApp/
      - ./pm2-sapper/:/usr/src/app/
    ports:
      - 80:3000

